# Generated by Django 4.2.2 on 2025-02-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prestado',
            field=models.BooleanField(default=False),
        ),
    ]
