# Generated by Django 4.2.2 on 2025-03-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_producto_prestado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='codigo',
            new_name='id',
        ),
    ]
