# Generated by Django 4.2.2 on 2025-03-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_codigo_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='AAA000', max_length=6),
            preserve_default=False,
        ),
    ]
