# Generated by Django 4.2.2 on 2025-03-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
