# Generated by Django 4.2.2 on 2024-11-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Completo', models.CharField(max_length=30)),
                ('Documento', models.IntegerField()),
                ('Telefono', models.IntegerField()),
                ('Domicilio', models.CharField(max_length=100)),
            ],
        ),
    ]
