# Generated by Django 4.2.2 on 2024-08-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Documento', models.IntegerField(max_length=12)),
                ('Iden_persona', models.IntegerField(max_length=10)),
                ('Telefono', models.IntegerField(max_length=12)),
                ('Domicilio', models.CharField(max_length=20)),
            ],
        ),
    ]
