# Generated by Django 4.2.2 on 2025-02-28 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socios',
            name='Asociado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('cuota1', models.BooleanField(default=False)),
                ('cuota2', models.BooleanField(default=False)),
                ('cuota3', models.BooleanField(default=False)),
                ('cuota4', models.BooleanField(default=False)),
                ('cuota5', models.BooleanField(default=False)),
                ('cuota6', models.BooleanField(default=False)),
                ('completas', models.BooleanField(default=False)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='socios.socios')),
            ],
        ),
    ]
