# Generated by Django 4.2.2 on 2024-09-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socios',
            old_name='Nombre',
            new_name='Nombre_Completo',
        ),
    ]
