# Generated by Django 4.2.2 on 2025-02-17 08:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '__first__'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.PositiveIntegerField()),
                ('fecha_extraccion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('prestatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
                ('productos', models.ManyToManyField(to='stock.producto')),
            ],
        ),
    ]
