# Generated by Django 4.2.2 on 2025-02-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
