# Generated by Django 4.2.2 on 2025-02-27 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_prestamo_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_extraccion',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
